AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing infra for APIs and their documentation (using S3-hosted Swagger UI).

Parameters:
  MediaDomainName:
    Type: String
    Description: Domain name to be used for the API.
    Default: media.<my.domain.com>
  RootHostedZone:
    Type: String
    Description: Root Hosted Zone
    Default: <hosted zone id>
  MediaBucketName:
    Type: String
    Description: Media bucket name
    Default: media.<my.domain.com>

  # DocsDomainName:
  #   Type: String
  #   Description: Domain name to be used for the docs.
  #   Default: docs.<my.domain.com>
  # DocsBucketName:
  #   Type: String
  #   Description: Bucket name to be used for hosting API docs.
  #   Default: <my_project_name>-docs

Resources:
  # Cognito stack
  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./cognito/template.yaml
      Parameters:
        RawMediaBucketName: !Sub ${MediaBucketName}-raw
        ProcessedMediaBucketName: !Sub ${MediaBucketName}-processed

  # S3 stack
  S3Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./s3/template.yaml
      Parameters:
        RawMediaBucketName: !Sub ${MediaBucketName}-raw
        ProcessedMediaBucketName: !Sub ${MediaBucketName}-processed

  # API stacks
  ApiV1Stack:
    Type: AWS::Serverless::Application
    DependsOn:
      - S3Stack
    Properties:
      Location: ./api/v1/template.yaml
      Parameters:
        RawMediaBucketName: !Sub ${MediaBucketName}-raw
        ProcessedMediaBucketName: !Sub ${MediaBucketName}-processed
        MainUserPoolId: !GetAtt CognitoStack.Outputs.MainUserPoolIdOutput
        MainUserPoolArn: !GetAtt CognitoStack.Outputs.MainUserPoolArnOutput

  # Cloud Front stack
  CloudFrontStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - ApiV1Stack
    Properties:
      Location: ./cloud_front/template.yaml
      Parameters:
        MediaApiId: !GetAtt ApiV1Stack.Outputs.MediaApiIdOutput
        MediaApiStage: !GetAtt ApiV1Stack.Outputs.MediaApiStageOutput
        MediaDomainName: !Ref MediaDomainName
        RootHostedZone: !Ref RootHostedZone
# DocsDomainName: !Ref DocsDomainName
#   # Docs stacks
#   DocsStack:
#     Type: AWS::Serverless::Application
#     Properties:
#       Location: ./docs/template.yaml
#       Parameters:
#         DocsBucketName: !Ref DocsBucketName
#         DocsDomainName: !Ref DocsDomainName
#         RootHostedZone: !Ref RootHostedZone

# Outputs:
#   DocsCloudFrontDistributionIdOutput:
#     Description: Docs CloudFront Distribution ID
#     Value: !GetAtt DocsStack.Outputs.DocsCloudFrontDistributionIdOutput
#   DocsBucketNameOutput:
#     Description: API Docs S3 bucket
#     Value: !GetAtt DocsStack.Outputs.DocsBucketNameOutput
