AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Public broadcasting service (PBS) Cloud Front infra

Parameters:
  PbsApiId:
    Type: String
    Description: Pbs Api Id

  PbsApiStage:
    Type: String
    Description: Pbs Api Stage

  PbsDomainName:
    Type: String
    Description: Pbs domain name

  RootHostedZone:
    Type: String
    Description: Root Hosted Zone

Resources:
  # Certificates
  PbsCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref PbsDomainName
      ValidationMethod: DNS

  # Cloud Front
  PbsCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref PbsDomainName
        Origins:
          - DomainName: !Sub "${PbsApiId}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: !Sub "/${PbsApiStage}"
            Id: PbsApiId
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: "https-only"
        Enabled: true
        # DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          TargetOriginId: PbsApiId
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - POST
            - DELETE
            - PUT
            - PATCH
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: "none"
        ViewerCertificate:
          AcmCertificateArn: !Ref PbsCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: "http2"

  # Record Set
  PbsApiRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref RootHostedZone
      Name: !Ref PbsDomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Hosted Zone ID
        DNSName: !GetAtt PbsCloudFrontDistribution.DomainName
