openapi: 3.0.1
info:
  title: Bluecollarverse Media API
  description: Meida API for the project
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://pbs.bluecollarverse.com
paths:
  /media/{filename}:
    get:
      tags:
        - Media
      summary: Retrieve media from S3
      description: Retrieve media (photos and video) from an S3 bucket
      operationId: retrieveMedia
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
          description: Filename of the media to retrieve
        - name: extension
          in: query
          required: true
          schema:
            type: string
          description: Extension of the media to retrieve
        - name: size
          in: query
          required: true
          schema:
            type: string
          description: Optional size of the media to retrieve
      responses:
        '200':
          description: >-
            Media successfully retrieved. In practicality, a 302 redirect is
            expected.
        '302':
          description: Successfully retrieved the media URL.
          headers:
            Location:
              schema:
                type: string
                format: uri
        '400':
          description: Bad Request, usually due to invalid parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: File not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '503':
          description: External service unavailable or request rejected.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '504':
          description: Request to external service timed out.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
        - NONE: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RetrieveMediaFunction.Arn}/invocations
  /upload:
    post:
      tags:
        - Media
      summary: Generate a presigned URL for S3 upload
      description: >-
        Generate a presigned URL to upload media (photos and video) into an S3
        bucket
      operationId: mediaUpload
      parameters:
        - in: header
          name: username
          required: true
          schema:
            type: string
          description: The username from the authorizer
        - in: query
          name: content_type
          required: true
          schema:
            type: string
          description: The content type of the media to be uploaded
      responses:
        '200':
          description: Successfully generated the presigned URL.
          content:
            application/json:
              schema:
                type: object
                properties:
                  uploadURL:
                    type: string
                  filename:
                    type: string
        '400':
          description: Bad Request, usually due to missing or invalid event data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Unauthorized access, usually due to missing or invalid username.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: An unexpected error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '503':
          description: External service unavailable or request rejected.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '504':
          description: Request to external service timed out.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      security:
        - MainCognitoAuthorizer: []
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadMediaFunction.Arn}/invocations
components:
  securitySchemes:
    MainCognitoAuthorizer:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://<your-cognito-domain>/oauth2/authorize
          tokenUrl: https://<your-cognito-domain>/oauth2/token
          scopes: {}
    NONE:
      type: apiKey
      name: none
      in: header
  schemas:
    error:
      title: Error
      type: object
      description: Object representing an error.
      required:
        - error
      properties:
        error:
          type: string
          description: A human-readable message providing more details about the error.
          example: Internal service error.
