openapi: 3.0.1
info:
  title: Bluecollarverse Media API
  description: Meida API for the project
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://media.bluecollarverse.com
paths:
  /media/{filename}:
    $ref: "paths/media.yaml"
  /upload:
    $ref: "paths/upload.yaml"
components:
  securitySchemes:
    $ref: "components/schemas/securitySchemes.yaml"
