openapi: 3.0.1
info:
  title: Bluecollarverse Media API
  description: Meida API for the project
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://media.bluecollarverse.com/v1
paths:
  /{filename}:
    $ref: "paths/root.yaml"
  /upload:
    $ref: "paths/upload.yaml"
